// default package
// Generated Mar 2, 2017 1:23:57 PM by Hibernate Tools 5.2.1.Final
package model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Auteur generated by hbm2java
 */
@Entity
@Table(name = "auteur", schema = "public")
public class Auteur implements java.io.Serializable {

	private int idAuteur;
	private String nom;
	private String prenom;
	private Set sources = new HashSet(0);

	public Auteur() {
	}

	public Auteur(int idAuteur) {
		this.idAuteur = idAuteur;
	}

	public Auteur(int idAuteur, String nom, String prenom, Set sources) {
		this.idAuteur = idAuteur;
		this.nom = nom;
		this.prenom = prenom;
		this.sources = sources;
	}

	@Id

	@Column(name = "id_auteur", unique = true, nullable = false)
	public int getIdAuteur() {
		return this.idAuteur;
	}

	public void setIdAuteur(int idAuteur) {
		this.idAuteur = idAuteur;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom")
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "auteurs")
	public Set getSources() {
		return this.sources;
	}

	public void setSources(Set sources) {
		this.sources = sources;
	}

}
