// default package
// Generated Mar 2, 2017 1:23:57 PM by Hibernate Tools 5.2.1.Final
package model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Categorie generated by hbm2java
 */
@Entity
@Table(name = "categorie", schema = "public")
public class Categorie implements java.io.Serializable {

	private int idCategorie;
	private String nom;
	private Set sources = new HashSet(0);

	public Categorie() {
	}

	public Categorie(int idCategorie) {
		this.idCategorie = idCategorie;
	}

	public Categorie(int idCategorie, String nom, Set sources) {
		this.idCategorie = idCategorie;
		this.nom = nom;
		this.sources = sources;
	}

	@Id

	@Column(name = "id_categorie", unique = true, nullable = false)
	public int getIdCategorie() {
		return this.idCategorie;
	}

	public void setIdCategorie(int idCategorie) {
		this.idCategorie = idCategorie;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@ManyToMany(fetch = FetchType.LAZY, mappedBy = "categories")
	public Set getSources() {
		return this.sources;
	}

	public void setSources(Set sources) {
		this.sources = sources;
	}

}
