// default package
// Generated Mar 2, 2017 1:23:57 PM by Hibernate Tools 5.2.1.Final
package model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Edition generated by hbm2java
 */
@Entity
@Table(name = "edition", schema = "public")
public class Edition implements java.io.Serializable {

	private int idEdition;
	private Source source;
	private String nom;
	private Set sources = new HashSet(0);

	public Edition() {
	}

	public Edition(int idEdition, Source source) {
		this.idEdition = idEdition;
		this.source = source;
	}

	public Edition(int idEdition, Source source, String nom, Set sources) {
		this.idEdition = idEdition;
		this.source = source;
		this.nom = nom;
		this.sources = sources;
	}

	@Id

	@Column(name = "id_edition", unique = true, nullable = false)
	public int getIdEdition() {
		return this.idEdition;
	}

	public void setIdEdition(int idEdition) {
		this.idEdition = idEdition;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_source", nullable = false)
	public Source getSource() {
		return this.source;
	}

	public void setSource(Source source) {
		this.source = source;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "edition")
	public Set getSources() {
		return this.sources;
	}

	public void setSources(Set sources) {
		this.sources = sources;
	}

}
