// default package
// Generated Mar 2, 2017 1:23:57 PM by Hibernate Tools 5.2.1.Final
package model;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Type generated by hbm2java
 */
@Entity
@Table(name = "type", schema = "public")
public class Type implements java.io.Serializable {

	private int idType;
	private String nom;
	private Set sources = new HashSet(0);

	public Type() {
	}

	public Type(int idType) {
		this.idType = idType;
	}

	public Type(int idType, String nom, Set sources) {
		this.idType = idType;
		this.nom = nom;
		this.sources = sources;
	}

	@Id

	@Column(name = "id_type", unique = true, nullable = false)
	public int getIdType() {
		return this.idType;
	}

	public void setIdType(int idType) {
		this.idType = idType;
	}

	@Column(name = "nom")
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "type")
	public Set getSources() {
		return this.sources;
	}

	public void setSources(Set sources) {
		this.sources = sources;
	}

}
